#!/bin/sh
unset IFS
set -euf

DEFAULT_TASK='test'

audit() {
    docker_scout
    snyk
}

bashate() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 .venv/bin/bashate -i E006
}

docker_build() {
    docker build -t mcandre/valgrind-peak --load .
}

docker_publish() {
    docker push mcandre/valgrind-peak
}

docker_scout() {
    docker scout cves -e mcandre/valgrind-peak
}

funk() {
    command funk .
}

lint() {
    bashate
    funk
    shellcheck
    shfmt
    slick
}

shellcheck() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shellcheck
}

shfmt() {
    stank -print0 -exInterp zsh . |
        xargs -0 -n 1 shfmt -w -i 4
}

slick() {
    stank -print0 -sh . |
        xargs -0 -n 1 slick
}

snyk() {
    command snyk test --all-projects --exclude=requirements.txt
    command snyk test --command=.venv/bin/python3
}

test() {
    docker run --rm mcandre/valgrind-peak echo hello
}

if [ "$#" -eq 0 ]; then
    "$DEFAULT_TASK"
    exit
fi

for ARG in "$@"; do
    "$ARG"
done
